apiVersion: batch/v1
kind: CronJob
metadata:
  name: django-clearsessions
spec:
  schedule: "0 3 1 * *"
  timeZone: "Europe/Moscow"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  startingDeadlineSeconds: 3600
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: clearsessions
              image: django_app:latest
              imagePullPolicy: IfNotPresent
              command: ["python", "manage.py", "clearsessions"]
              envFrom:
                - secretRef:
                    name: django-secret
