apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrate
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: django-migrate
          image: django_app:latest
          imagePullPolicy: IfNotPresent
          command: ["python", "manage.py", "migrate", "--noinput"]
          envFrom:
            - secretRef:
                name: django-secret
